package memory

import (
	"context"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"time"

	"agent-memory-mcp/internal/app"
	"agent-memory-mcp/internal/core"
	"agent-memory-mcp/internal/store/sqlite"
)

type Service struct {
	store *sqlite.Store
}

func NewService(store *sqlite.Store) app.MemoryService {
	return &Service{store: store}
}

func (s *Service) ResolveRepo(path string) (string, error) {
	// For simplicity in the port, if the path has a .git, we could hash it.
	// We'll just use the basename of the directory for this minimal version,
	// or fallback to 'default'. Python resolves upwards looking for .git.
	p, err := filepath.Abs(path)
	if err != nil {
		p = path
	}
	repoID := filepath.Base(p)
	if repoID == "." || repoID == "" {
		repoID = "default"
	}
	
	err = s.store.UpsertRepo(context.Background(), repoID, p)
	return repoID, err
}

func (s *Service) Remember(repoID, kind, content, source string, metadata map[string]any) (string, bool, error) {
	return s.store.InsertMemory(context.Background(), repoID, kind, content, source, metadata, false)
}

func (s *Service) Search(ctx context.Context, query string, repoID *string, kinds []string, limit int) ([]core.Memory, error) {
	return s.store.Search(ctx, query, repoID, kinds, limit)
}

func (s *Service) ListMemories(ctx context.Context, repoID *string, kind *string, limit int) ([]core.Memory, error) {
	return s.store.ListMemories(ctx, repoID, kind, limit)
}

func (s *Service) ListRepos(ctx context.Context) ([]core.RepoListing, error) {
	repos, err := s.store.ListReposDB(ctx)
	if err != nil {
		return nil, err
	}
	var res []core.RepoListing
	for _, r := range repos {
		errCount := s.store.FailureErrorCount(ctx, r.ID)
		health := "HEALTHY"
		if errCount > 0 {
			health = "CRITICAL"
		}
		res = append(res, core.RepoListing{
			ID:         r.ID,
			Path:       r.Path,
			Health:     health,
			ErrorCount: errCount,
		})
	}
	return res, nil
}

func (s *Service) GetRepoContext(ctx context.Context, repoID string) (core.RepoContext, error) {
	return s.store.GetRepoContext(ctx, repoID)
}

func (s *Service) MarkFailureResolved(ctx context.Context, repoID, signature string) (bool, error) {
	return s.store.MarkFailureResolved(ctx, repoID, signature)
}

func (s *Service) Forget(ctx context.Context, memoryID, signature, repoID string) (int, error) {
	return s.store.Forget(ctx, memoryID, signature, repoID)
}

func (s *Service) RefreshRelevance(ctx context.Context, repoID *string) (int, int, error) {
	// Classify noise first
	noiseCount, err := s.store.ClassifyNoise(ctx, 7)
	if err != nil {
		return 0, 0, err
	}
	relCount, err := s.store.RefreshRelevance(ctx, repoID)
	return relCount, noiseCount, err
}

func (s *Service) GenerateContextFile(ctx context.Context, repoID string, projectPath string) error {
	path, err := s.BuildContextFile(ctx, repoID, projectPath)
	_ = path
	return err
}

func (s *Service) BuildContextFile(ctx context.Context, repoID string, projectPath string) (string, error) {
	rc, err := s.GetRepoContext(ctx, repoID)
	if err != nil {
		return "", err
	}
	
	now := time.Now().UTC().Format(time.RFC3339)
	content := fmt.Sprintf("# Agent Memory Context (auto-generated)\n# Project: %s\n# Last updated: %s\n# Do not edit — regenerated by agent-memory-mcp\n\n", repoID, now)
	
	if rc.Decisions != "(none)" && rc.Decisions != "" {
		content += "## Key Decisions\n" + rc.Decisions + "\n\n"
	}
	if rc.Failures != "(none)" && rc.Failures != "" {
		content += "## Known Issues\n" + rc.Failures + "\n\n"
	}
	if rc.Facts != "(none)" && rc.Facts != "" {
		content += "## Project Facts\n" + rc.Facts + "\n\n"
	}

	outDir := filepath.Join(projectPath, ".agent-memory")
	os.MkdirAll(outDir, 0755)
	outFile := filepath.Join(outDir, "context.md")
	err = ioutil.WriteFile(outFile, []byte(content), 0644)
	return outFile, err
}

func (s *Service) SmartContext(ctx context.Context, repoID, task string, maxTokens int) (core.SmartContext, error) {
	mems, err := s.store.Search(ctx, task, &repoID, nil, 10)
	if err != nil {
		return core.SmartContext{}, err
	}
	
	est := 0
	for _, m := range mems {
		est += len(m.Content) / 4
	}
	
	return core.SmartContext{
		Memories: mems,
		TokenEstimate: est,
		SystemPromptFragment: "Injected context summary.",
	}, nil
}

func (s *Service) GlobalSearch(ctx context.Context, query string, kinds []string, limit int) ([]core.Memory, error) {
	return s.store.GlobalSearch(ctx, query, kinds, limit)
}

func (s *Service) GetPatternReport(ctx context.Context, repoID *string) (map[string]any, error) {
	return s.store.GetPatternReport(ctx, repoID)
}

func (s *Service) FailureHotspots(ctx context.Context, limit int) ([]map[string]any, error) {
	return s.store.FailureHotspots(ctx, limit)
}

func (s *Service) GetRelatedMemories(ctx context.Context, memoryID string, limit int) ([]core.Memory, error) {
	return s.store.GetRelatedMemories(ctx, memoryID, limit)
}

func (s *Service) RecordFeedback(ctx context.Context, memoryID string, useful bool, comment string) error {
	return s.store.RecordFeedback(ctx, memoryID, useful, comment)
}
