package memory

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"agent-memory-mcp/internal/app"
	"agent-memory-mcp/internal/core"
	"agent-memory-mcp/internal/patterns"
	"agent-memory-mcp/internal/projects"
	"agent-memory-mcp/internal/smartctx"
	"agent-memory-mcp/internal/store/sqlite"
)

type Service struct {
	store      *sqlite.Store
	detector   *patterns.Detector
	correlator *patterns.Correlator
	packer     *smartctx.Packer
}

func NewService(store *sqlite.Store) app.MemoryService {
	return &Service{
		store:      store,
		detector:   patterns.NewDetector(store),
		correlator: patterns.NewCorrelator(store),
		packer:     smartctx.NewPacker(store),
	}
}

func (s *Service) ResolveRepo(path string) (string, error) {
	rootPath, err := projects.FindProjectRoot(path)
	if err != nil {
		rootPath = path
	}
	repoID := filepath.Base(rootPath)
	if repoID == "." || repoID == "" {
		repoID = "default"
	}

	err = s.store.UpsertRepo(context.Background(), repoID, rootPath)
	return repoID, err
}

func (s *Service) Remember(repoID, kind, content, source string, metadata map[string]any) (string, bool, error) {
	return s.store.InsertMemory(context.Background(), repoID, kind, content, source, metadata, false)
}

func (s *Service) Search(ctx context.Context, query string, repoID *string, kinds []string, limit int) ([]core.Memory, error) {
	mems, err := s.store.Search(ctx, query, repoID, kinds, limit)
	if err == nil {
		for _, m := range mems {
			s.store.RecordAccess(ctx, m.ID, "search", query, "", "")
		}
	}
	return mems, err
}

func (s *Service) ListMemories(ctx context.Context, repoID *string, kind *string, limit int) ([]core.Memory, error) {
	return s.store.ListMemories(ctx, repoID, kind, limit)
}

func (s *Service) ListRepos(ctx context.Context) ([]core.RepoListing, error) {
	repos, err := s.store.ListReposDB(ctx)
	if err != nil {
		return nil, err
	}
	res := []core.RepoListing{}
	for _, r := range repos {
		errCount := s.store.FailureErrorCount(ctx, r.ID)
		health := "HEALTHY"
		if errCount > 0 {
			health = "CRITICAL"
		}
		res = append(res, core.RepoListing{
			ID:         r.ID,
			Path:       r.Path,
			Health:     health,
			ErrorCount: errCount,
		})
	}
	return res, nil
}

func (s *Service) GetRepoContext(ctx context.Context, repoID string) (core.RepoContext, error) {
	return s.store.GetRepoContext(ctx, repoID)
}

func (s *Service) MarkFailureResolved(ctx context.Context, repoID, signature string) (bool, error) {
	return s.store.MarkFailureResolved(ctx, repoID, signature)
}

func (s *Service) Forget(ctx context.Context, memoryID, signature, repoID string) (int, error) {
	return s.store.Forget(ctx, memoryID, signature, repoID)
}

func (s *Service) RefreshRelevance(ctx context.Context, repoID *string) (int, int, error) {
	// Stubbed per L7 because store.ClassifyNoise and RefreshRelevance crash or are incomplete
	return 0, 0, nil
}

func (s *Service) GenerateContextFile(ctx context.Context, repoID string, projectPath string) error {
	path, err := s.BuildContextFile(ctx, repoID, projectPath)
	_ = path
	return err
}

func (s *Service) BuildContextFile(ctx context.Context, repoID string, projectPath string) (string, error) {
	rc, err := s.GetRepoContext(ctx, repoID)
	if err != nil {
		return "", err
	}

	now := time.Now().UTC().Format(time.RFC3339)
	content := fmt.Sprintf("# Agent Memory Context (auto-generated)\n# Project: %s\n# Last updated: %s\n# Do not edit — regenerated by agent-memory-mcp\n\n", repoID, now)

	if rc.Decisions != "(none)" && rc.Decisions != "" {
		content += "## Key Decisions\n" + rc.Decisions + "\n\n"
	}
	if rc.Failures != "(none)" && rc.Failures != "" {
		content += "## Known Issues\n" + rc.Failures + "\n\n"
	}
	if rc.Facts != "(none)" && rc.Facts != "" {
		content += "## Project Facts\n" + rc.Facts + "\n\n"
	}

	outDir := filepath.Join(projectPath, ".agent-memory")
	os.MkdirAll(outDir, 0755)
	outFile := filepath.Join(outDir, "context.md")
	err = os.WriteFile(outFile, []byte(content), 0644)
	return outFile, err
}

// SmartContext now delegates to the proper Packer with token budgeting.
func (s *Service) SmartContext(ctx context.Context, repoID, task string, maxTokens int) (core.SmartContext, error) {
	return s.packer.Pack(ctx, repoID, task, maxTokens)
}

func (s *Service) GlobalSearch(ctx context.Context, query string, kinds []string, limit int) ([]core.Memory, error) {
	mems, err := s.store.GlobalSearch(ctx, query, kinds, limit)
	if err == nil {
		for _, m := range mems {
			s.store.RecordAccess(ctx, m.ID, "search", query, "", "")
		}
	}
	return mems, err
}

// GetPatternReport now delegates to the real PatternDetector.
func (s *Service) GetPatternReport(ctx context.Context, repoID *string) (map[string]any, error) {
	return s.detector.GetReport(ctx, repoID)
}

func (s *Service) FailureHotspots(ctx context.Context, limit int) ([]map[string]any, error) {
	return s.store.FailureHotspots(ctx, limit)
}

// GetRelatedMemories now delegates to the real Correlator.
func (s *Service) GetRelatedMemories(ctx context.Context, memoryID string, limit int) ([]core.Memory, error) {
	return s.correlator.GetRelated(ctx, memoryID, limit)
}

func (s *Service) FindSimilarFailures(ctx context.Context, repoID string, limit int) ([]core.Memory, error) {
	return s.correlator.FindSimilarFailures(ctx, repoID, limit)
}

func (s *Service) RecordFeedback(ctx context.Context, memoryID string, useful bool, comment string) error {
	return s.store.RecordFeedback(ctx, memoryID, useful, comment)
}

func (s *Service) Export(ctx context.Context, repoID *string) ([]core.Memory, error) {
	// ListMemories returns all memories without limiting if limit is large enough,
	// but we might want a dedicated function. Let's just use ListMemories with a huge limit for MVP
	return s.store.ListMemories(ctx, repoID, nil, 1000000)
}

func (s *Service) Import(ctx context.Context, memories []core.Memory) (int, error) {
	count := 0
	for _, m := range memories {
		err := s.store.ImportMemory(ctx, m)
		if err != nil {
			// Continue importing other memories even if one fails
			fmt.Printf("Failed to import memory %s: %v\n", m.ID, err)
			continue
		}
		count++
	}
	return count, nil
}
